# Generated by Django 5.2.8 on 2025-11-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=25)),
                ('MRP', models.IntegerField()),
                ('Product_Material', models.CharField(max_length=15)),
                ('serial_Number', models.CharField(max_length=10)),
                ('review', models.DateField()),
                ('Phone_Number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
